### ISSUE TITLE
Missing geometry file?

### ISSUE THREAD

**Issue by apeck12** [chuckie82/pysingfel#103]
It seems that unit tests in test_diffraction.py and for the detector class are failing due to the missing geometry file: ‘PNCCD::CalibV1/Camp.0:pnCCD.1/geometry/0-end.data'. Tests that rely on a user-defined detector pass.

**Comment by fredericpoitevin** [comment]
Hi Ariana, sorry I forgot to point you here: https://github.com/chuckie82/pysingfel/blob/master/docs/quick_start.md

This should solve it

**Comment by apeck12** [comment]
Sorry I missed that, and thanks for the tip! I found that those files resolved all but one of the unit test errors. The test that continues to fail is in detector/test_autoranging_detector.py, with error:

======================================================================
ERROR: Test existence of pedestals.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cds/sw/ds/ana/conda2/inst/envs/ps-4.0.9/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/cds/home/a/apeck/pysingfel/pysingfel/detector/tests/test_autoranging_detector.py", line 75, in test_pedestal_nonzero
    assert np.sum(abs(self.det.pedestals[:])) > np.finfo(float).eps
  File "/cds/home/a/apeck/pysingfel/pysingfel/detector/lcls.py", line 194, in pedestals
    return self._get_calib_constants("pedestals")
  File "/cds/home/a/apeck/pysingfel/pysingfel/detector/lcls.py", line 188, in _get_calib_constants
    "".format(name))
RuntimeError: No pedestals available for this detector

----------------------------------------------------------------------

**Comment by chuckie82** [comment]
It looks like we should add some epix10k files:
'/input/lcls/xcsx35617/Epix10ka2M::CalibV1/XcsEndstation.0:Epix10ka2M.0/geometry/0-end.data'
I will add them.

**Comment by chuckie82** [comment]
@apeck12 I updated lcls.tar.gz.
Could you try sourcing download.sh again and run pytest?

**Comment by apeck12** [comment]
I'm still receiving the same error: "RuntimeError: No pedestals available for this detector" in the unit tests from test_autoranging_detector.py. When I generate a detector object from the epix10k files, the calibration constants (pedestals, pixel_rms, etc.) don't get added. I'm using psana2, so the relevant function seems to be:

https://github.com/chuckie82/pysingfel/blob/bef7ac9d47020e8f019f3cc79b6a0ec53790c2d9/pysingfel/detector/lcls.py#L177

**Comment by chuckie82** [comment]
If you are using psana2, calib constants get fetched from MongoDB:
from psana.pscalib.calib.MDBWebUtils import calib_constants

Option 1) would be to ask Mikhail about adding xcsx35617 epix10ka2M calibration
Option 2) disable pytest for autoranging detector test
Option 3) use psana1

**Comment by apeck12** [comment]
The solution was to disable the autoranging detector unit test for PY3/psana2 (assuming that psana1 corresponds to PY2) since xcsx35617 epix10ka2M calibration constants are not yet available in psana2.
